name: Daily Bible Sender

on:
  schedule:
    # 한국 시간(KST) 오전 5시는 UTC 기준 전날 20:00입니다.
    - cron: '31 20 * * *'
  workflow_dispatch: # 수동으로 실행해볼 수 있는 버튼을 활성화합니다.

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      KO_CHAT_ID: ${{ secrets.KO_CHAT_ID }}
      EN_CHAT_ID: ${{ secrets.EN_CHAT_ID }}
      MN_CHAT_ID: ${{ secrets.MN_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache : 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python send_bible_passage_all.py